[package]
name = "rpm-rs"
version = "0.6.0"
authors = [
    "René Richter <richterrettich@gmail.com>",
    "Bernhard Schuster <bernhard@ahoi.io>"
]
edition = "2018"
license = "Apache-2.0"
description = "A pure rust library for building and parsing RPM's"
homepage = "https://github.com/Richterrettich/rpm-rs"
repository = "https://github.com/Richterrettich/rpm-rs"
readme = "README.md"
keywords = ["RPM", "packaging"]
categories = ["parsing", "development-tools"]

[lib]
name = "rpm"

[dependencies]
thiserror = "1"
nom = "7.0"
num-traits = "0.2"
num-derive = "0.3"
num = "0.4"
enum-display-derive = "0.1"
cpio = "0.2"
# consider migrating to flate2
libflate = "1"
sha2 = "0.9"
md-5 = "0.9"
sha1 = "0.6"
rand = { version = "0.8" }
pgp = { version = "0.7", optional = true }
chrono = "0.4"
log = "0.4"

[dev-dependencies]
rsa = { version = "^0.5.0" }
rsa-der = { version = "^0.2.1" }
env_logger = "0.9"
itertools = "0.10"
serial_test = "0.5"

[features]
default = ["signature-pgp"]

signature-pgp = ["signature-meta", "pgp"]
signature-meta = []
test-with-podman = ["signature-meta"]